# This is a basic workflow to help you get started with Actions

name: Deploy-ALZ

env:
      RESOURCEGROUPNAME: "rg-ipam-06"  
      VNETNAME: "vnet-ipam-06"    
      SUBSCRIPTIONID: "ef620d24-2d5d-4e63-aaf9-e42cafb44dfb"  
      REGION: "uksouth" 
      
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  alz:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: true
          
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript: |
            $uri = 'https://fa-ipam-04.azurewebsites.net/api/RegisterAddressSpace?code=R9O27f/s1UzaSrQHDBbsuRs2LG9SKU9uW7J1YEaarX3iER4kxjWCCA=='
            $uri
            $body = @{
                  'InputObject' = @{
                        'ResourceGroup' = ${{ env.RESOURCEGROUPNAME }}
                        'VirtualNetworkName' = ${{ env.VNETNAME }}
                  }
            } | ConvertTo-Json
            $body
#            $params = @{
#                  'Uri'         = $uri
#                  'Method'      = 'POST'
#                  'ContentType' = 'application/json'
#                  'Body'        = $Body
#            }
#            $params
#            $Result = Invoke-RestMethod @params
#            New-AzResourceGroup -Name ${{ env.RESOURCEGROUPNAME }} -Location ${{ env.REGION }} -Force
#            New-AzVirtualNetwork -Name ${{ env.VNETNAME }} -ResourceGroupName ${{ env.RESOURCEGROUPNAME }} -Location ${{ env.REGION }} -AddressPrefix $Result.NetworkAddress
          azPSVersion: latest 
          errorActionPreference: Stop
          
