# ToDo
#   Create RG with Bicep
#   Create VNet with Bicep (accepting parameter of address space)
#   Allowed regions / translation table e.g. uksouth - uks
#   Store access key in vault
#   Invoke workflow with different parameters

name: Deploy-ALZ

env:
      CGSUBID: "cg01lzp001"
      REGIONID: "uks"
      REGIONNAME: "uksouth" 
      
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ none ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Job-Build-ALZ:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: true
          
#      - name: Save variables
#        run: |
#            echo "RGNAME=rg-${{ env.CGSUBID }}-${{ env.REGIONID }}-network" >> $GITHUB_ENV 
#            echo "VNETNAME=vnet-${{ env.CGSUBID }}-${{ env.REGIONID }}-01" >> $GITHUB_ENV          
          
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            $regionName = "${{ env.REGIONNAME }}" 
            $uri = 'https://fa-ipam-04.azurewebsites.net/api/RegisterAddressSpace?code=R9O27f/s1UzaSrQHDBbsuRs2LG9SKU9uW7J1YEaarX3iER4kxjWCCA=='
            $body = @{
              'InputObject' = @{
                'ResourceGroup' = "rg-${{ env.CGSUBID }}-${{ env.REGIONID }}-network"
                'VirtualNetworkName' = "vnet-${{ env.CGSUBID }}-${{ env.REGIONID }}-01"
              }
            } | ConvertTo-Json
            $body
            $params = @{
                  'Uri'         = $uri
                  'Method'      = 'POST'
                  'ContentType' = 'application/json'
                  'Body'        = $Body
            }
            $params
            $Result = Invoke-RestMethod @params
            echo "ADDRESSRANGE=$Result.NetworkAddress" >> $GITHUB_ENV    
#            New-AzResourceGroup -Name $rgName -Location $regionName -Force
#            New-AzVirtualNetwork -Name $vnetName -ResourceGroupName $rgName -Location $regionName -AddressPrefix $Result.NetworkAddress
          azPSVersion: latest 
          errorActionPreference: Stop
          
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: subscription
          # Override the Subscription Id set by Azure Login.
          #subscriptionId: # optional
          # Specify the Id for the Management Group, only required for Management Group Deployments.
          #managementGroupId: # optional
          # Provide the target region, only required for management Group or Subscription deployments.
          region: ${{ env.REGIONNAME }}
          # Provide the name of a resource group, only required for resource Group deployments.
          #resourceGroupName: 'rg-${{ env.CGSUBID }}-${{ env.REGIONID }}-network'
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./main.bicep
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          #deploymentMode: Incremental
          parameters: 
            cgSubId=${{ env.CGSUBID }}
            regionId=${{ env.REGIONID }}
            regionName=${{ env.REGIONNAME }}
            addressRange=${{ env.ADDRESSRANGE }}
          # Specify whether to fail the action if some data is written to stderr stream of az cli. Valid values are: true, false
          #failOnStdErr: # optional, default is true
