# ToDo
#   Allowed regions / translation table e.g. uksouth - uks
#   Store access key in vault
#   Invoke workflow with different parameters
#   Handle different target subscriptions

name: Deploy-ALZ

env:
      CGSUBID: "cg05lzp001"
      REGIONNAME: "uksouth" 
      
on:
  push:
    branches: [ none ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:    # Allows you to run this workflow manually from the Actions tab

jobs:
  Job-Build-ALZ:
    runs-on: windows-latest

    steps:             
      - name: Check Out Repository              # Check out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v2
      
      - name: Azure Login                       # Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true     
          
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            $uri = 'https://fa-ipam-04.azurewebsites.net/api/RegisterAddressSpace?code=R9O27f/s1UzaSrQHDBbsuRs2LG9SKU9uW7J1YEaarX3iER4kxjWCCA=='
            $body = @{
              'InputObject' = @{
                'ResourceGroup' = "rg-${{ env.CGSUBID }}-${{ env.REGIONNAME }}-network"
                'VirtualNetworkName' = "vnet-${{ env.CGSUBID }}-${{ env.REGIONNAME }}-01"
              }
            } | ConvertTo-Json
            $params = @{
                  'Uri'         = $uri
                  'Method'      = 'POST'
                  'ContentType' = 'application/json'
                  'Body'        = $Body
            }
            $Result = Invoke-RestMethod @params
            $networkAddress = $Result.NetworkAddress
            New-AzDeployment -Location ${{ env.REGIONNAME }} -TemplateFile ./main.bicep `
                  -cgSubId ${{ env.CGSUBID }} `
                  -regionName ${{ env.REGIONNAME }} `
                  -addressRange $networkAddress
          azPSVersion: latest 
          errorActionPreference: Stop
          
